/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `ApplicationPassword`;

CREATE TABLE `ApplicationPassword` (
  `passwordID` INT NOT NULL PRIMARY KEY,
  `app` INT NULL,
  `title` TEXT NULL,
  `url` TEXT NULL,
  `username` TEXT NULL,
  `password` TEXT NOT NULL)
 ENGINE=InnoDB;

/*
ALTER TABLE `ApplicationPassword`
  ADD CONSTRAINT `ApplicationPassword_app_fk`
    FOREIGN KEY (`app`)
    REFERENCES `Application` (`app_id`)
*/

