/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Application`;

CREATE TABLE `Application` (
  `appId` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `executablePath` TEXT NOT NULL,
  `executableHash` TEXT NOT NULL)
 ENGINE=InnoDB;

