/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Application`;

CREATE TABLE `Application` (
  `app_id` INT NOT NULL PRIMARY KEY,
  `executable_path` TEXT NOT NULL,
  `executable_hash` TEXT NOT NULL)
 ENGINE=InnoDB;

